#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "Rostislav Raykov"
# set email per repo

[ui]
default-command = "log"

[[--scope]]
--when.commands = ["diff", "show"]
[--scope.ui]
# https://github.com/jj-vcs/jj/blob/v0.25.0/docs/config.md#processing-contents-to-be-paged
pager = "delta"
# NOTE: this is required when using `delta` as a pager
diff-formatter = ":git"

[aliases]
credit = ["file", "annotate"]
# Move closest bookmark forward to current position
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]

[revset-aliases]
# Local commits not yet pushed
"local" = "all() ~ ancestors(remote_bookmarks())"

# Find closest bookmark to a commit
"closest_bookmark(to)" = "heads(::to & bookmarks())"

# trunk() by default resolves to the latest 'main'/'master' remote bookmark. May
# require customization for repos like nixpkgs.
'trunk()' = 'latest((present(main) | present(master)) & remote_bookmarks())'

# anything which is a work in progress according to the description
wip = 'description(regex:"^\\[(wip|WIP|todo|TODO)\\]|(wip|WIP|todo|TODO):?")'

# anything by a specific user, based on substring search of name or email
'user(x)' = 'author(x) | committer(x)'

# closest rev which is ok to be pushed (mutable, having description, not empty, not a merge)
'closest_pushable(to)' = 'heads(::to & mutable() & ~description(exact:"") & (~empty() | merges()))'
