[".config/zellij/plugins/harpoon.wasm"]
type = "file"
url = "https://github.com/Nacho114/harpoon/releases/download/v0.3.0/harpoon.wasm"
checksum.sha256 = "7f8cf57a71f1dbbbd115337a31638780d7e18e9b876def1c81c970188caa32f2"

[".config/zellij/plugins/zjframes.wasm"]
type = "file"
url = "https://github.com/dj95/zjstatus/releases/download/v0.24.0/zjframes.wasm"
checksum.sha256 = "044ed6c1784ee98c6d22ba7530644dc16c7ee2d1681c34ee603237358e123bda"

[".config/zellij/plugins/zjstatus.wasm"]
type = "file"
url = "https://github.com/dj95/zjstatus/releases/download/v0.24.0/zjstatus.wasm"
checksum.sha256 = "1ccedece1ded62cf3e209be690cdd39ca6fb9e8228ed71a951f6507f9956669b"

[".config/zellij/plugins/zjstatus-hints.wasm"]
type = "file"
url = "https://github.com/myah-mitchell/zjstatus-hints/releases/download/v0.3.1/zjstatus-hints.wasm"
checksum.sha256 = "0f4294f80d18b764e9c6dca4f9bd0928381725f422bab83f5c4a4ac31f22923f"
