theme = "rose_pine"

[editor]
line-number = "relative"
bufferline = "multiple"
true-color = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false
git-ignore = false

[editor.lsp]
display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "error"

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position", "position-percentage"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"] # cancel selection with esc
