[packages.darwin]
taps = [
    "1password/tap",
    "borgbackup/tap",
    "chiselstrike/tap",
    "codecrafters-io/tap",
    "hashicorp/tap",
    "hcavarsan/kftray",
    "homebrew/bundle",
    "homebrew/cask-fonts",
    "homebrew/cask-versions",
    "homebrew/services",
    "libsql/sqld",
    "macos-fuse-t/homebrew-cask"
]
brews = [
    # Run your GitHub Actions locally
    "act",
    # Simple, modern, secure file encryption
    "age",
    # Improved shell history for zsh, bash, fish and nushell
    "atuin",
    # General-purpose data compression with high compression ratio
    "xz",
    # Automate deployment, configuration, and upgrading
    "ansible",
    # Checks ansible playbooks for practices and behaviour
    "ansible-lint",
    # Library for manipulating PNG images
    "libpng",
    # Image format providing lossless and lossy compression for web images
    "webp",
    # New file format for still image compression
    "jpeg-xl",
    # Collection of portable C++ source libraries
    "boost",
    # Standard XML representation system for technical documents
    "docbook",
    # Source-code syntax highlighter
    "source-highlight",
    # Formatter/translator for text files to numerous formats
    "asciidoc",
    # Text processor and publishing toolchain for AsciiDoc
    "asciidoctor",
    # Archival front-end
    "atool",
    # Tool for generating GNU Standards-compliant Makefiles
    "automake",
    # Official Amazon AWS command-line interface
    "awscli",
    # C library implementing the SSH2 protocol
    "libssh2",
    # Regular expressions library
    "oniguruma",
    # Clone of cat(1) with syntax highlighting and Git integration
    "bat",
    # Garbage collector for C and C++
    "bdw-gc",
    # Compiler infrastructure and toolchain library for WebAssembly
    "binaryen",
    # Parser generator
    "bison",
    # Simple wrapper script for the Borg backup software
    "borgmatic",
    # Yet another cross-platform graphical process/system monitor
    "bottom",
    # Glorious Glasgow Haskell Compilation System
    "ghc",
    # Command-line interface for Cabal and Hackage
    "cabal-install",
    # Software library to render fonts
    "freetype",
    # XML-based font configuration API for X Windows
    "fontconfig",
    # GNU internationalization (i18n) and localization (l10n) library
    "gettext",
    # Core application library for C
    "glib",
    # Low-level library for pixel manipulation
    "pixman",
    # Vector graphics library with cross-device output support
    "cairo",
    # Easily generate Instruments traces for your rust crate
    "cargo-instruments",
    # Object-file caching compiler wrapper
    "ccache",
    # Manage your dotfiles across multiple diverse machines, securely
    "chezmoi",
    # Cross-platform make
    "cmake",
    # GNU File, Shell, and Text utilities
    "coreutils",
    # Lightweight, framework-agnostic database migration tool
    "dbmate",
    # USB programmer
    "dfu-util",
    # Display user-friendly message boxes from shell scripts
    "dialog",
    # Load/unload environment variables based on $PWD
    "direnv",
    # Minimal, fast alternative to 'du -sh'
    "diskus",
    # Tool for exploring each layer in a docker image
    "dive",
    # Command-line tool for DigitalOcean
    "doctl",
    # Command-line DNS client
    "dog",
    # More intuitive version of du in rust
    "dust",
    # Build automation tool for the container era
    "earthly",
    # Generic library support script
    "libtool",
    # Programming language for highly scalable real-time systems
    "erlang",
    # Functional metaprogramming aware language built on Erlang VM
    "elixir",
    # Serial flasher utility for Espressif SoCs and modules based on esptool.py
    "espflash",
    # Command-line tool to interact with exercism.io
    "exercism",
    # Perl lib for reading and writing EXIF metadata
    "exiftool",
    # Modern, maintained replacement for ls
    "eza",
    # Simple, fast and user-friendly alternative to find
    "fd",
    # Validating, recursive, caching DNS resolver
    "unbound",
    # GNU Transport Layer Security (TLS) Library
    "gnutls",
    # OpenType text shaping engine
    "harfbuzz",
    # Framework for layout and rendering of i18n text
    "pango",
    # OCR (Optical Character Recognition) engine
    "tesseract",
    # H.265/HEVC encoder
    "x265",
    # Scaling, colorspace conversion, and dithering library
    "zimg",
    # Play, record, convert, and stream audio and video
    "ffmpeg",
    # Collection of GNU find, xargs, and locate
    "findutils",
    # User-friendly command-line shell for UNIX-like operating systems
    "fish",
    # Fast and simple Node.js version manager
    "fnm",
    # Command-line fuzzy finder written in Go
    "fzf",
    # GNU compiler collection
    "gcc",
    # Interpreter for PostScript and PDF
    "ghostscript",
    # Distributed revision control system
    "git",
    # Syntax-highlighting pager for git and diff output
    "git-delta",
    # Git extension for versioning large files
    "git-lfs",
    # Statically typed language for the Erlang VM
    "gleam",
    # Callback framework for C++
    "libsigc++",
    # C++ interface to glib
    "glibmm",
    # C++ interface to glib
    "glibmm@2.66",
    # Command-line option parsing utility
    "gnu-getopt",
    # GNU implementation of the famous stream editor
    "gnu-sed",
    # GNU Pretty Good Privacy (PGP) package
    "gnupg",
    # Open source programming language to build simple/reliable/efficient software
    "go",
    # Generate introspection data for GObject libraries
    "gobject-introspection",
    # Library access to GnuPG
    "gpgme",
    # Library for manipulating JPEG-2000 images
    "jasper",
    # Library to render SVG files using Cairo
    "librsvg",
    # Graph visualization software from AT&T and Bell Labs
    "graphviz",
    # Colorize logfiles and command output
    "grc",
    # GNU grep, egrep and fgrep
    "grep",
    # Command-line tool for generating regular expressions
    "grex",
    # Protocol buffers (Google's data interchange format)
    "protobuf",
    # Next generation open source RPC library and framework
    "grpc",
    # GNU Ubiquitous Intelligent Language for Extensions
    "guile",
    # Tool for glamorous shell scripts
    "gum",
    # Cross-platform program for developing Haskell projects
    "haskell-stack",
    # Kubernetes package manager
    "helm",
    # Easy plain text accounting with command-line, terminal and web UIs
    "hledger",
    # Improved top (interactive process viewer)
    "htop",
    # Command-line benchmarking tool
    "hyperfine",
    # Database of common MIME types
    "shared-mime-info",
    # ISO/IEC 23008-12:2017 HEIF file format decoder and encoder
    "libheif",
    # LLVM's OpenMP runtime library
    "libomp",
    # Library for reading RAW files from digital photo cameras
    "libraw",
    # Tools and libraries to manipulate images in many formats
    "imagemagick",
    # GNU utilities for networking
    "inetutils",
    # CLI for managing resources in InfluxDB v2
    "influxdb-cli",
    # Manage your Java environment
    "jenv",
    # Image manipulation library
    "jpeg",
    # Lightweight and flexible command-line JSON processor
    "jq",
    # Handy way to save and run project-specific commands
    "just",
    # Kubernetes CLI To Manage Your Clusters In Style!
    "k9s",
    # Easy way to access the system keyring service from python
    "keyring",
    # Kubernetes command-line interface
    "kubernetes-cli",
    # Kubernetes controller and tool for one-way encrypted Secrets
    "kubeseal",
    # Template-free customization of Kubernetes YAML manifests
    "kustomize",
    # Linear Algebra PACKage
    "lapack",
    # Command-line, double-entry accounting tool
    "ledger",
    # Postgres C API library
    "libpq",
    # Library that provides automatic proxy configuration management
    "libproxy",
    # Apache Pulsar C++ library
    "libpulsar",
    # Adds spatial SQL capabilities to SQLite
    "libspatialite",
    # C websockets server library
    "libwebsockets",
    # C++ wrapper for libxml
    "libxml++",
    # Next-gen compiler infrastructure
    "llvm@17",
    # Powerful, lightweight programming language
    "lua",
    # Package manager for the Lua programming language
    "luarocks",
    # Keep your Mac's application settings in sync
    "mackup",
    # Securely transfers data between computers
    "magic-wormhole",
    # Utility for directing compilation
    "make",
    # Mac App Store command-line interface
    "mas",
    # Replacement for the old crypt package and crypt(1) command
    "mcrypt",
    # Simple tool to make locally trusted development certificates
    "mkcert",
    # Remote terminal application
    "mosh",
    # Platform built on V8 to build network applications
    "node",
    # Neon CLI tool
    "neonctl",
    # Ambitious Vim-fork focused on extensibility and agility
    "neovim",
    # Port scanning utility for large networks
    "nmap",
    # Libraries for security-enabled client and server applications
    "nss",
    # Optimized BLAS library
    "openblas",
    # Development kit for the Java programming language
    "openjdk@11",
    # Cryptography and SSL/TLS Toolkit
    "openssl@1.1",
    # 7-Zip (high compression file archiver) implementation
    "p7zip",
    # PDF rendering library (based on the xpdf-3.0 code base)
    "poppler",
    # Search PDFs for strings matching a regular expression
    "pdfgrep",
    # Python package management tool
    "poetry",
    # Modern replacement for ps written in Rust
    "procs",
    # Go support for Google's protocol buffers
    "protoc-gen-go",
    # Utilities for manipulating PostScript documents
    "psutils",
    # Python version management
    "pyenv",
    # Interpreted, interactive, object-oriented programming language
    "python@3.10",
    # Interpreted, interactive, object-oriented programming language
    "python@3.9",
    # Fast, efficient and secure backup program
    "restic",
    # Search tool like grep and The Silver Searcher
    "ripgrep",
    # Utility that provides fast incremental file transfer
    "rsync",
    # Rust toolchain installer
    "rustup",
    # Command-line tool for the Amazon S3 service
    "s3cmd",
    # Intuitive find & replace CLI
    "sd",
    # Static analysis and lint tool, for (ba)sh scripts
    "shellcheck",
    # Editor of encrypted files
    "sops",
    # Command-line interface for https://speedtest.net bandwidth tests
    "speedtest-cli",
    # Cross-shell prompt for astronauts
    "starship",
    # User interface to the TELNET protocol
    "telnet",
    # Clean C library for processing UTF-8 Unicode data
    "utf8proc",
    # Terminal multiplexer
    "tmux",
    # Program that allows you to count code, quickly
    "tokei",
    # CLI tool that moves files or folder to the trash
    "trash",
    # Build, bundle & ship your Rust WASM application to the web
    "trunk",
    # Markup-based typesetting system
    "typst",
    # Formatter for typst
    "typstfmt",
    # Extremely fast Python package installer and resolver, written in Rust
    "uv",
    # Vi 'workalike' with many additional features
    "vim",
    # Your favorite rust -> wasm workflow tool!
    "wasm-pack",
    # Executes a program periodically, showing output fullscreen
    "watch",
    # Internet file retriever
    "wget",
    # Tools for the WireGuard secure network tunnel
    "wireguard-tools",
    # HTTP benchmarking tool
    "wrk",
    # Friendly and fast tool for sending HTTP requests
    "xh",
    # Fast CSV toolkit written in Rust
    "xsv",
    # JavaScript package manager
    "yarn",
    # Process YAML, JSON, XML, CSV and properties documents from the CLI
    "yq",
    # Feature-rich command-line audio/video downloader
    "yt-dlp",
    # Fast static site generator in a single binary with everything built-in
    "zola",
    # Shell extension to navigate your filesystem faster
    "zoxide",
    # Pluggable terminal workspace, with terminal multiplexer as the base feature
    "zellij",    
    # Deduplicating archiver with compression and authenticated encryption
    "borgbackup/tap/borgbackup-fuse",
    "chiselstrike/tap/turso",
    # CodeCrafters CLI
    "codecrafters-io/tap/codecrafters",
]
casks = [
    # Command-line helper for the 1Password password manager
    "1password-cli@beta",
    # Password manager
    "1password@beta",
    # AirPods companion app
    "airbuddy",
    # GraphQL client
    "altair-graphql-client",
    # Inspect application bundles
    "apparency",
    # Tool to flash OS images to SD cards & USB drives
    "balenaetcher",
    # E-books management software
    "calibre",
    # Multi-platform client-side cloud file encryption tool
    "cryptomator",
    # Database manager
    "dataflare",
    # Voice and text chat software
    "discord",
    # App to build and share containerised applications and microservices
    "docker",
    # Calendar software
    "fantastical",
    # Collaborative team software
    "figma",
    # Web browser
    "firefox",
    "font-anonymice-powerline",
    "font-dejavu-sans-mono-for-powerline",
    "font-droid-sans-mono-for-powerline",
    "font-fira-code",
    "font-fira-mono-for-powerline",
    "font-inconsolata-dz-for-powerline",
    "font-inconsolata-for-powerline",
    "font-inconsolata-g-for-powerline",
    "font-iosevka",
    "font-jetbrains-mono",
    "font-liberation-mono-for-powerline",
    "font-menlo-for-powerline",
    "font-meslo-for-powerline",
    "font-meslo-lg-nerd-font",
    "font-monofur-for-powerline",
    "font-noto-emoji",
    "font-noto-mono-for-powerline",
    "font-roboto-mono-for-powerline",
    "font-sauce-code-pro-nerd-font",
    "font-source-code-pro",
    "font-source-code-pro-for-powerline",
    "font-source-sans-pro",
    "font-source-serif-pro",
    "font-ubuntu-mono-derivative-powerline",
    # Git client for simultaneous branches on top of your existing workflow
    "gitbutler",
    # Git interface focused on visual interaction
    "gitup",
    # Web browser
    "google-chrome",
    # Open-source video transcoder
    "handbrake",
    # Menu bar manager
    "jordanbaird-ice",
    # Spot and merge differences in text and image files or folders
    "kaleidoscope",
    # End-to-end encryption software
    "keybase",
    # Music services manager
    "lastfm",
    # Code notebooks for Elixir developers
    "livebook",
    # Software for Logitech devices
    "logitech-options",
    # Utility for pairing devices with Unifying receivers
    "logitech-unifying",
    # File system integration
    "macfuse",
    # LibFUSE implementation that doesn't use kernel extensions
    "fuse-t",
    # Speech recognition tool
    "macwhisper",
    # Tool to control external monitor brightness & volume
    "monitorcontrol",
    # Re-mounts write-protected NTFS volumes
    "mounty",
    # Free and open-source RSS reader
    "netnewswire",
    # Audiobook manager for Audible users
    "openaudible",
    # Open source build of Lens Kubernetes IDE
    "openlens",
    # Replacement for Docker Desktop
    "orbstack",
    # HTTP client that helps testing and describing APIs
    "paw",
    # Home media player
    "plex",
    # GUI client for PostgreSQL databases
    "postico",
    # Quick Look generator for Markdown files
    "qlmarkdown",
    # QMK Toolbox
    "qmk-toolbox",
    # Quick Look plugin for CSV files
    "quicklook-csv",
    # Quick Look plugin for JSON files
    "quicklook-json",
    # Archive manager for data compression and backups
    "rar",
    # Control your tools with a few keystrokes
    "raycast",
    # Tool that provides consistent, highly configurable symbols for apps
    "sf-symbols",
    # Instant messaging application focusing on security
    "signal",
    # Team communication and collaboration software
    "slack",
    # System monitor for the menu bar
    "stats",
    # Video game digital distribution service
    "steam",
    # Native GUI tool for relational databases
    "tableplus",
    # Tool for liberating data tables trapped inside PDF files
    "tabula",
    # Mesh VPN based on WireGuard
    "tailscale",
    # Messaging app with a focus on speed and security
    "telegram",
    # Unpacks archive files
    "the-unarchiver",
    # File transfer application
    "transmit",
    # Keyboard configurator
    "via",
    # Calling and messaging application focusing on security
    "viber",
    # Virtualization tool
    "virtualbuddy",
    # OpenVPN client with AppleScript support
    "viscosity",
    # Open-source code editor
    "visual-studio-code",
    # Code editor
    "visual-studio-code@insiders",
    # Desktop Backup Client for Borg
    "vorta",
    # Rust-based terminal
    "warp",
    # GPU-accelerated cross-platform terminal emulator and multiplexer
    "wezterm",
    # Native desktop client for WhatsApp
    "whatsapp@beta",
    # REST, GraphQL and gRPC client
    "yaak",
    # Multiplayer code editor
    "zed",
]

[[packages.darwin.mas]]
name = "1Password for Safari"
id = 1569813296

[[packages.darwin.mas]]
name = "Bakery"
id = 1575220747

[[packages.darwin.mas]]
name = "CiderTV"
id = 1065907486

[[packages.darwin.mas]]
name = "Convusic"
id = 1591366129

[[packages.darwin.mas]]
name = "DaisyDisk"
id = 411643860

[[packages.darwin.mas]]
name = "Day One"
id = 1055511498

[[packages.darwin.mas]]
name = "Developer"
id = 640199958

[[packages.darwin.mas]]
name = "Dropover"
id = 1355679052

[[packages.darwin.mas]]
name = "Exporter"
id = 1099120373

[[packages.darwin.mas]]
name = "Fresh Cards"
id = 1523398835

[[packages.darwin.mas]]
name = "Go Map!!"
id = 592990211

[[packages.darwin.mas]]
name = "Hush"
id = 1544743900

[[packages.darwin.mas]]
name = "Ice Cubes"
id = 6444915884

[[packages.darwin.mas]]
name = "Iconic"
id = 1582751983

[[packages.darwin.mas]]
name = "Jayson"
id = 1468691718

[[packages.darwin.mas]]
name = "Kaleidoscope"
id = 587512244

[[packages.darwin.mas]]
name = "Keynote"
id = 409183694

[[packages.darwin.mas]]
name = "Keys Multiplatform"
id = 1494642810

[[packages.darwin.mas]]
name = "Kindle"
id = 302584613

[[packages.darwin.mas]]
name = "Landmarks"
id = 6446065798

[[packages.darwin.mas]]
name = "MakePass"
id = 1450989464

[[packages.darwin.mas]]
name = "Messenger"
id = 1480068668

[[packages.darwin.mas]]
name = "miele-lxiv"
id = 988332475

[[packages.darwin.mas]]
name = "MusicHarbor"
id = 1440405750

[[packages.darwin.mas]]
name = "MusicSmart"
id = 1512195368

[[packages.darwin.mas]]
name = "NepTunes"
id = 1006739057

[[packages.darwin.mas]]
name = "Notchmeister"
id = 1599169747

[[packages.darwin.mas]]
name = "Numbers"
id = 409203825

[[packages.darwin.mas]]
name = "Pages"
id = 409201541

[[packages.darwin.mas]]
name = "Paprika Recipe Manager 3"
id = 1303222628

[[packages.darwin.mas]]
name = "Pi-hole Remote"
id = 1515445551

[[packages.darwin.mas]]
name = "Pixelmator Pro"
id = 1289583905

[[packages.darwin.mas]]
name = "Playgrounds"
id = 1496833156

[[packages.darwin.mas]]
name = "Shazam"
id = 897118787

[[packages.darwin.mas]]
name = "Soor"
id = 1439731526

[[packages.darwin.mas]]
name = "StopTheMadness"
id = 1376402589

[[packages.darwin.mas]]
name = "TestFlight"
id = 899247664

[[packages.darwin.mas]]
name = "Things"
id = 904280696

[[packages.darwin.mas]]
name = "Vidimote"
id = 1585702412

[[packages.darwin.mas]]
name = "Vinegar"
id = 1591303229

[[packages.darwin.mas]]
name = "Wayback Machine"
id = 1472432422

[[packages.darwin.mas]]
name = "WireGuard"
id = 1451685025

[[packages.darwin.mas]]
name = "WorldWideWeb"
id = 1621370168
