[packages.darwin]
taps = [
    "1password/tap",
    "borgbackup/tap",
    "chiselstrike/tap",
    "codecrafters-io/tap",
    "hashicorp/tap",
    "hcavarsan/kftray",
    "libsql/sqld",
    "macos-fuse-t/homebrew-cask",
    "qmk/qmk",
    "nikitabobko/tap",
    "FelixKratz/formulae",
]
brews = [
    # Simple, modern, secure file encryption
    "age",
    # Improved shell history for zsh, bash, fish and nushell
    "atuin",
    # Tool for generating GNU Standards-compliant Makefiles
    "automake",
    # Clone of cat(1) with syntax highlighting and Git integration
    "bat",
    # Compiler infrastructure and toolchain library for WebAssembly
    "binaryen",
    # Simple wrapper script for the Borg backup software
    "borgmatic",
    # Yet another cross-platform graphical process/system monitor
    "bottom",
    # Manage your dotfiles across multiple diverse machines, securely
    "chezmoi",
    # Cross-platform make
    "cmake",
    # GNU File, Shell, and Text utilities
    "coreutils",
    # Display user-friendly message boxes from shell scripts
    "dialog",
    # Load/unload environment variables based on $PWD
    "direnv",
    # Tool for exploring each layer in a docker image
    "dive",
    # More intuitive version of du in rust
    "dust",
    # Functional metaprogramming aware language built on Erlang VM
    "elixir",
    # Serial flasher utility for Espressif SoCs and modules based on esptool.py
    "espflash",
    # Modern, maintained replacement for ls
    "eza",
    # Simple, fast and user-friendly alternative to find
    "fd",
    # Play, record, convert, and stream audio and video
    "ffmpeg",
    # Collection of GNU find, xargs, and locate
    "findutils",
    # User-friendly command-line shell for UNIX-like operating systems
    "fish",
    # Command-line fuzzy finder written in Go
    "fzf",
    # GNU compiler collection
    "gcc",
    # Distributed revision control system
    "git",
    # Syntax-highlighting pager for git and diff output
    "git-delta",
    # Git extension for versioning large files
    "git-lfs",
    # Statically typed language for the Erlang VM
    "gleam",
    # GNU Pretty Good Privacy (PGP) package
    "gnupg",
    # Open source programming language to build simple/reliable/efficient software
    "go",
    # Command-line tool for generating regular expressions
    "grex",
    # Tool for glamorous shell scripts
    "gum",
    # Easy plain text accounting with command-line, terminal and web UIs
    "hledger",
    # Improved top (interactive process viewer)
    "htop",
    # Command-line benchmarking tool
    "hyperfine",
    # Tools and libraries to manipulate images in many formats
    "imagemagick",
    # GNU utilities for networking
    "inetutils",
    # Lightweight and flexible command-line JSON processor
    "jq",
    # Handy way to save and run project-specific commands
    "just",
    # Next-gen compiler infrastructure
    "llvm@17",
    # Powerful, lightweight programming language
    "lua",
    # Package manager for the Lua programming language
    "luarocks",
    # Keep your Mac's application settings in sync
    "mackup",
    # Securely transfers data between computers
    "magic-wormhole",
    # Utility for directing compilation
    "make",
    # Mac App Store command-line interface
    "mas",
    # Remote terminal application
    "mosh",
    # Ambitious Vim-fork focused on extensibility and agility
    "neovim",
    # Port scanning utility for large networks
    "nmap",
    # Search PDFs for strings matching a regular expression
    "pdfgrep",
    # Modern replacement for ps written in Rust
    "procs",
    # Fast, efficient and secure backup program
    "restic",
    # Search tool like grep and The Silver Searcher
    "ripgrep",
    # Rust toolchain installer
    "rustup",
    # Intuitive find & replace CLI
    "sd",
    # Static analysis and lint tool, for (ba)sh scripts
    "shellcheck",
    # Editor of encrypted files
    "sops",
    # Cross-shell prompt for astronauts
    "starship",
    # Program that allows you to count code, quickly
    "tokei",
    # CLI tool that moves files or folder to the trash
    "trash",
    # Build, bundle & ship your Rust WASM application to the web
    "trunk",
    # Markup-based typesetting system
    "typst",
    # Beautiful and reliable typst code formatter
    "typstyle",
    # Extremely fast Python package installer and resolver, written in Rust
    "uv",
    # Vi 'workalike' with many additional features
    "vim",
    # Your favorite rust -> wasm workflow tool!
    "wasm-pack",
    # Executes a program periodically, showing output fullscreen
    "watch",
    # Internet file retriever
    "wget",
    # Tools for the WireGuard secure network tunnel
    "wireguard-tools",
    # HTTP benchmarking tool
    "wrk",
    # Friendly and fast tool for sending HTTP requests
    "xh",
    # CSV CLI magician written in Rust
    "xan",
    # Process YAML, JSON, XML, CSV and properties documents from the CLI
    "yq",
    # Fast static site generator in a single binary with everything built-in
    "zola",
    # Shell extension to navigate your filesystem faster
    "zoxide",
    # Pluggable terminal workspace, with terminal multiplexer as the base feature
    "zellij",
    # Deduplicating archiver with compression and authenticated encryption
    "borgbackup/tap/borgbackup-fuse",
    "chiselstrike/tap/turso",
    # CodeCrafters CLI
    "codecrafters-io/tap/codecrafters",
    # Language Server Protocol for Markdown
    "marksman",
    # Blazing fast terminal file manager written in Rust, based on async I/O
    "yazi",
    # Git-compatible distributed version control system
    "jj",
    # Post-modern modal text editor
    "helix",
    # Microsoft Azure CLI 2.0
    "azure-cli",
    # Custom macOS statusbar with shell plugin, interaction and graph support
    "sketchybar",
    # Language Server for typos-cli
    "typos-lsp",
    # Terminal slideshow tool
    "presenterm",
    # Syntax-aware linter for prose
    "vale",
    # QR Code generation
    "qrencode",
    # Rainbows and unicorns in your console!
    "lolcat",
    # Modern shell for the GitHub era
    "nushell",
    # Diff that understands syntax
    "difftastic",
    # Git hook and pre-commit lint manager
    "hk",
    # Polyglot runtime manager (asdf rust clone)
    "mise",
    # Apjanke's fork of the classic cowsay project
    "cowsay"
]
casks = [
    # Command-line helper for the 1Password password manager
    "1password-cli@beta",
    # Password manager
    "1password@beta",
    # AirPods companion app
    "airbuddy",
    # Inspect application bundles
    "apparency",
    # Tool to flash OS images to SD cards & USB drives
    "balenaetcher",
    # E-books management software
    "calibre",
    # Multi-platform client-side cloud file encryption tool
    "cryptomator",
    # Database manager
    "dataflare",
    # Voice and text chat software
    "discord",
    # Calendar software
    "fantastical",
    # Collaborative team software
    "figma",
    # Web browser
    "firefox",
    "font-anonymice-powerline",
    "font-dejavu-sans-mono-for-powerline",
    "font-droid-sans-mono-for-powerline",
    "font-fira-code",
    "font-fira-mono-for-powerline",
    "font-inconsolata-dz-for-powerline",
    "font-inconsolata-for-powerline",
    "font-inconsolata-g-for-powerline",
    "font-iosevka",
    "font-jetbrains-mono",
    "font-jetbrains-mono-nerd-font",
    "font-liberation-mono-for-powerline",
    "font-menlo-for-powerline",
    "font-meslo-for-powerline",
    "font-meslo-lg-nerd-font",
    "font-monofur-for-powerline",
    "font-noto-emoji",
    "font-noto-mono-for-powerline",
    "font-roboto-mono-for-powerline",
    "font-sauce-code-pro-nerd-font",
    "font-source-code-pro",
    "font-source-code-pro-for-powerline",
    "font-ubuntu-mono-derivative-powerline",
    # Git client for simultaneous branches on top of your existing workflow
    "gitbutler",
    # Git interface focused on visual interaction
    "gitup",
    # Web browser
    "google-chrome",
    # Open-source video transcoder
    "handbrake-app",
    # Menu bar manager
    "jordanbaird-ice",
    # Spot and merge differences in text and image files or folders
    "kaleidoscope",
    # End-to-end encryption software
    "keybase",
    # Music services manager
    "lastfm",
    # Code notebooks for Elixir developers
    "livebook",
    # Software for Logitech devices
    "logi-options+",
    # File system integration
    "macfuse",
    # LibFUSE implementation that doesn't use kernel extensions
    "fuse-t",
    # Speech recognition tool
    "macwhisper",
    # Tool to control external monitor brightness & volume
    "monitorcontrol",
    # Re-mounts write-protected NTFS volumes
    "mounty",
    # Free and open-source RSS reader
    "netnewswire",
    # Audiobook manager for Audible users
    "openaudible",
    # Open source build of Lens Kubernetes IDE
    "openlens",
    # Replacement for Docker Desktop
    "orbstack",
    # Home media player
    "plex",
    # GUI client for PostgreSQL databases
    "postico",
    # Quick Look plugin for CSV files
    "quicklook-csv",
    # Quick Look plugin for JSON files
    "quicklook-json",
    # Archive manager for data compression and backups
    "rar",
    # Control your tools with a few keystrokes
    "raycast",
    # Tool that provides consistent, highly configurable symbols for apps
    "sf-symbols",
    # Instant messaging application focusing on security
    "signal",
    # Team communication and collaboration software
    "slack",
    # System monitor for the menu bar
    "stats",
    # Video game digital distribution service
    "steam",
    # Native GUI tool for relational databases
    "tableplus",
    # Tool for liberating data tables trapped inside PDF files
    "tabula",
    # Mesh VPN based on WireGuard
    "tailscale-app",
    # Messaging app with a focus on speed and security
    "telegram",
    # Unpacks archive files
    "the-unarchiver",
    # File transfer application
    "transmit",
    # Calling and messaging application focusing on security
    "viber",
    # Virtualization tool
    "virtualbuddy",
    # OpenVPN client with AppleScript support
    "viscosity",
    # Open-source code editor
    "visual-studio-code",
    # Code editor
    "visual-studio-code@insiders",
    # Desktop Backup Client for Borg
    "vorta",
    # Rust-based terminal
    "warp",
    # GPU-accelerated cross-platform terminal emulator and multiplexer
    "wezterm",
    # Native desktop client for WhatsApp
    "whatsapp@beta",
    # REST, GraphQL and gRPC client
    "yaak",
    # Multiplayer code editor
    "zed",
    # SketchyBar default font
    "font-hack-nerd-font",
    # Screen capturing tool
    "cleanshot",
    # Keyboard customiser
    "karabiner-elements",
]

[[packages.darwin.mas]]
name = "1Password for Safari"
id = 1569813296

[[packages.darwin.mas]]
name = "Bakery"
id = 1575220747

[[packages.darwin.mas]]
name = "CiderTV"
id = 1065907486

[[packages.darwin.mas]]
name = "Convusic"
id = 1591366129

[[packages.darwin.mas]]
name = "DaisyDisk"
id = 411643860

[[packages.darwin.mas]]
name = "Day One"
id = 1055511498

[[packages.darwin.mas]]
name = "Developer"
id = 640199958

[[packages.darwin.mas]]
name = "Dropover"
id = 1355679052

[[packages.darwin.mas]]
name = "Exporter"
id = 1099120373

[[packages.darwin.mas]]
name = "Fresh Cards"
id = 1523398835

[[packages.darwin.mas]]
name = "Go Map!!"
id = 592990211

[[packages.darwin.mas]]
name = "Hush"
id = 1544743900

[[packages.darwin.mas]]
name = "Ice Cubes"
id = 6444915884

[[packages.darwin.mas]]
name = "Iconic"
id = 1582751983

[[packages.darwin.mas]]
name = "Jayson"
id = 1468691718

[[packages.darwin.mas]]
name = "Keynote"
id = 409183694

[[packages.darwin.mas]]
name = "Keys Multiplatform"
id = 1494642810

[[packages.darwin.mas]]
name = "Kindle"
id = 302584613

[[packages.darwin.mas]]
name = "Landmarks"
id = 6446065798

[[packages.darwin.mas]]
name = "MakePass"
id = 1450989464

[[packages.darwin.mas]]
name = "Messenger"
id = 1480068668

[[packages.darwin.mas]]
name = "miele-lxiv"
id = 988332475

[[packages.darwin.mas]]
name = "MusicHarbor"
id = 1440405750

[[packages.darwin.mas]]
name = "MusicSmart"
id = 1512195368

[[packages.darwin.mas]]
name = "NepTunes"
id = 1006739057

[[packages.darwin.mas]]
name = "Notchmeister"
id = 1599169747

[[packages.darwin.mas]]
name = "Numbers"
id = 409203825

[[packages.darwin.mas]]
name = "Pages"
id = 409201541

[[packages.darwin.mas]]
name = "Paprika Recipe Manager 3"
id = 1303222628

[[packages.darwin.mas]]
name = "Pi-hole Remote"
id = 1515445551

[[packages.darwin.mas]]
name = "Pixelmator Pro"
id = 1289583905

[[packages.darwin.mas]]
name = "Playgrounds"
id = 1496833156

[[packages.darwin.mas]]
name = "Shazam"
id = 897118787

[[packages.darwin.mas]]
name = "Soor"
id = 1439731526

[[packages.darwin.mas]]
name = "StopTheMadness"
id = 1376402589

[[packages.darwin.mas]]
name = "TestFlight"
id = 899247664

[[packages.darwin.mas]]
name = "Things"
id = 904280696

[[packages.darwin.mas]]
name = "Vidimote"
id = 1585702412

[[packages.darwin.mas]]
name = "Vinegar"
id = 1591303229

[[packages.darwin.mas]]
name = "Wayback Machine"
id = 1472432422

[[packages.darwin.mas]]
name = "WireGuard"
id = 1451685025

[[packages.darwin.mas]]
name = "WorldWideWeb"
id = 1621370168
