[packages.darwin]
taps = [
    "homebrew/bundle",
    "1password/tap",
    "borgbackup/tap",
    "chiselstrike/tap",
    "hashicorp/tap",
    "homebrew/cask-fonts",
    "homebrew/cask-versions",
    "homebrew/services",
]
brews = [ 
    # Run your GitHub Actions locally
    "act",
    # A simple, modern and secure encryption tool
    "age",
    # Automate deployment, configuration, and upgrading
    "ansible",
    # Checks ansible playbooks for practices and behaviour
    "ansible-lint",
    # Protocol buffers (Google's data interchange format)
    "protobuf",
    # Interpreted, interactive, object-oriented programming language
    "python@3.10",
    # Formatter/translator for text files to numerous formats
    "asciidoc",
    # Text processor and publishing toolchain for AsciiDoc
    "asciidoctor",
    # Archival front-end
    "atool",
    # Tool for generating GNU Standards-compliant Makefiles
    "automake",
    # Clone of cat(1) with syntax highlighting and Git integration
    "bat",
    # Compiler infrastructure and toolchain library for WebAssembly
    "binaryen",
    # Simple wrapper script for the Borg backup software
    "borgmatic",
    # Easily generate Instruments traces for your rust crate
    "cargo-instruments",
    # Cross-platform make
    "cmake",
    # GNU File, Shell, and Text utilities
    "coreutils",
    # Compiler for writing C extensions for the Python language
    "cython",
    # Secure runtime for JavaScript and TypeScript
    "deno",
    # USB programmer
    "dfu-util",
    # Display user-friendly message boxes from shell scripts
    "dialog",
    # Load/unload environment variables based on $PWD
    "direnv",
    # Minimal, fast alternative to 'du -sh'
    "diskus",
    # Tool for exploring each layer in a docker image
    "dive",
    # Command-line tool for DigitalOcean
    "doctl",
    # Command-line DNS client
    "dog",
    # More intuitive version of du in rust
    "dust",
    # Functional metaprogramming aware language built on Erlang VM
    "elixir",
    # Serial flasher utility for Espressif SoCs and modules based on esptool.py
    "espflash",
    # Modern replacement for 'ls'
    "eza",
    # Command-line tool to interact with exercism.io
    "exercism",
    # Perl lib for reading and writing EXIF metadata
    "exiftool",
    # Simple, fast and user-friendly alternative to find
    "fd",
    # GNU compiler collection
    "gcc",
    # Play, record, convert, and stream audio and video
    "ffmpeg",
    # Collection of GNU find, xargs, and locate
    "findutils",
    # User-friendly command-line shell for UNIX-like operating systems
    "fish",
    # Command-line tools for fly.io services
    "flyctl",
    # Fast and simple Node.js version manager
    "fnm",
    # Command-line fuzzy finder written in Go
    "fzf",
    # GNU Pretty Good Privacy (PGP) package
    "gnupg",
    # GitHub command-line tool
    "gh",
    # Distributed revision control system
    "git",
    # Syntax-highlighting pager for git and diff output
    "git-delta",
    # Git extension for versioning large files
    "git-lfs",
    # Platform built on V8 to build network applications
    "node",
    # Command-line option parsing utility
    "gnu-getopt",
    # GNU implementation of the famous stream editor
    "gnu-sed",
    # Open source programming language to build simple/reliable/efficient software
    "go",
    # Pure Go implementation of jq
    "gojq",
    # Colorize logfiles and command output
    "grc",
    # GNU grep, egrep and fgrep
    "grep",
    # Command-line tool for generating regular expressions
    "grex",
    # Kubernetes package manager
    "helm",
    # Powerful, lightweight programming language
    "lua",
    # Convert source code to formatted text with syntax highlighting
    "highlight",
    # Easy plain text accounting with command-line, terminal and web UIs
    "hledger",
    # Improved top (interactive process viewer)
    "htop",
    # Simple zero-configuration command-line HTTP server
    "http-server",
    # Command-line benchmarking tool
    "hyperfine",
    # Interpreted, interactive, object-oriented programming language
    "python@3.9",
    # Tools and libraries to manipulate images in many formats
    "imagemagick",
    # GNU utilities for networking
    "inetutils",
    # Update of iperf: measures TCP, UDP, and SCTP bandwidth
    "iperf3",
    # JSON output from a shell
    "jo",
    # Lightweight and flexible command-line JSON processor
    "jq",
    # Handy way to save and run project-specific commands
    "just",
    # Kubernetes CLI To Manage Your Clusters In Style!
    "k9s",
    # Run local Kubernetes cluster in Docker
    "kind",
    # Tool to move from `docker-compose` to Kubernetes
    "kompose",
    # Kubernetes command-line interface
    "kubernetes-cli",
    # Kubernetes controller and tool for one-way encrypted Secrets
    "kubeseal",
    # Template-free customization of Kubernetes YAML manifests
    "kustomize",
    # Keep your Mac's application settings in sync
    "mackup",
    # Securely transfers data between computers
    "magic-wormhole",
    # Utility for directing compilation
    "make",
    # Mac App Store command-line interface
    "mas",
    # Fly through your shell history
    "mcfly",
    # Replacement for the old crypt package and crypt(1) command
    "mcrypt",
    # High performance static file server
    "miniserve",
    # Simple tool to make locally trusted development certificates
    "mkcert",
    # Remote terminal application
    "mosh",
    # Neon CLI tool
    "neonctl",
    # Ambitious Vim-fork focused on extensibility and agility
    "neovim",
    # Port scanning utility for large networks
    "nmap",
    # Batch rename utility
    "nomino",
    # 7-Zip (high compression file archiver) implementation
    "p7zip",
    # Search PDFs for strings matching a regular expression
    "pdfgrep",
    # Fast, disk space efficient package manager
    "pnpm",
    # Python package management tool
    "poetry",
    # Go support for Google's protocol buffers
    "protoc-gen-go",
    # Python version management
    "pyenv",
    # Search tool like grep and The Silver Searcher
    "ripgrep",
    # Utility that provides fast incremental file transfer
    "rsync",
    # Rust toolchain installer
    "rustup-init",
    # Intuitive find & replace CLI
    "sd",
    # Static analysis and lint tool, for (ba)sh scripts
    "shellcheck",
    # Simple and flexible tool for managing secrets
    "sops",
    # SMART hard drive monitoring
    "smartmontools",
    # Command-line interface for https://speedtest.net bandwidth tests
    "speedtest-cli",
    # Cross-shell prompt for astronauts
    "starship",
    # User interface to the TELNET protocol
    "telnet",
    # Tool to build, change, and version infrastructure
    "terraform",
    # Terminal multiplexer
    "tmux",
    # Program that allows you to count code, quickly
    "tokei",
    # CLI tool that moves files or folder to the trash
    "trash",
    # Build, bundle & ship your Rust WASM application to the web
    "trunk",
    # Tool for creating isolated virtual python environments
    "virtualenv",
    # Your favorite rust -> wasm workflow tool!
    "wasm-pack",
    # Executes a program periodically, showing output fullscreen
    "watch",
    # Internet file retriever
    "wget",
    # HTTP benchmarking tool
    "wrk",
    # Friendly and fast tool for sending HTTP requests
    "xh",
    # Fast CSV toolkit written in Rust
    "xsv",
    # Process YAML, JSON, XML, CSV and properties documents from the CLI
    "yq",
    # Fork of youtube-dl with additional features and fixes
    "yt-dlp",
    # Fast static site generator in a single binary with everything built-in
    "zola",
    # Shell extension to navigate your filesystem faster
    "zoxide",
    # Deduplicating archiver with compression and authenticated encryption
    "borgbackup/tap/borgbackup-fuse",
    "chiselstrike/tap/turso",
    # Vault
    "hashicorp/tap/vault",
]
casks = [
    # Password manager
    "1password-beta",
    # Command-line interface for 1Password
    "1password-cli",
    # AirPods companion app
    "airbuddy",
    # GraphQL client
    "altair-graphql-client",
    # Inspect application bundles
    "apparency",
    # Tool to flash OS images to SD cards & USB drives
    "balenaetcher",
    # Menu bar icon organiser
    "bartender",
    # E-books management software
    "calibre",
    # Multi-platform client-side cloud file encryption tool
    "cryptomator",
    # Voice and text chat software
    "discord",
    # Calendar software
    "fantastical",
    # Collaborative team software
    "figma",
    # Web browser
    "firefox",
    "font-anonymice-powerline",
    "font-dejavu-sans-mono-for-powerline",
    "font-droid-sans-mono-for-powerline",
    # Free monospaced font with programming ligatures
    "font-fira-code",
    "font-fira-mono-for-powerline",
    "font-inconsolata-dz-for-powerline",
    "font-inconsolata-for-powerline",
    "font-inconsolata-g-for-powerline",
    # Typeface made for developers
    "font-jetbrains-mono",
    "font-liberation-mono-for-powerline",
    "font-menlo-for-powerline",
    "font-meslo-for-powerline",
    "font-monofur-for-powerline",
    "font-noto-emoji",
    "font-noto-mono-for-powerline",
    "font-roboto-mono-for-powerline",
    # Developer targeted fonts with a high number of glyphs
    "font-sauce-code-pro-nerd-font",
    "font-source-code-pro",
    "font-source-code-pro-for-powerline",
    "font-source-sans-pro",
    "font-source-serif-pro",
    "font-ubuntu-mono-derivative-powerline",
    "font-iosevka",
    # Git interface focused on visual interaction
    "gitup",
    # Open-source video transcoder
    "handbrake",
    # Spot and merge differences in text and image files or folders
    "kaleidoscope",
    # End-to-end encryption software
    "keybase",
    # Music services manager
    "lastfm",
    # Code notebooks for Elixir developers
    "livebook",
    # Software for Logitech devices
    "logitech-options",
    # Utility for pairing devices with Unifying receivers
    "logitech-unifying",
    # File system integration
    "macfuse",
    # Re-mounts write-protected NTFS volumes
    "mounty",
    # Free and open-source RSS reader
    "netnewswire",
    # Audiobook manager for Audible users
    "openaudible",
    # Open source build of Lens Kubernetes IDE
    "openlens",
    # Replacement for Docker Desktop
    "orbstack",
    # HTTP client that helps testing and describing APIs
    "paw",
    # Home media player
    "plex",
    # GUI client for PostgreSQL databases
    "postico",
    # Quick Look generator for Markdown files
    "qlmarkdown",
    # Quick Look plugin for CSV files
    "quicklook-csv",
    # Quick Look plugin for JSON files
    "quicklook-json",
    # Archive manager for data compression and backups
    "rar",
    # Control your tools with a few keystrokes
    "raycast",
    # Tool that provides consistent, highly configurable symbols for apps
    "sf-symbols",
    # Instant messaging application focusing on security
    "signal",
    # Team communication and collaboration software
    "slack",
    # System monitor for the menu bar
    "stats",
    # Video game digital distribution service
    "steam",
    # Native GUI tool for relational databases
    "tableplus",
    # Tool for liberating data tables trapped inside PDF files
    "tabula",
    "tailscale",
    # Messaging app with a focus on speed and security
    "telegram",
    # Unpacks archive files
    "the-unarchiver",
    # File transfer application
    "transmit",
    # Calling and messaging application focusing on security
    "viber",
    # OpenVPN client with AppleScript support
    "viscosity",
    # Open-source code editor
    "visual-studio-code",
    # Multimedia player
    "vlc",
    # Desktop Backup Client for Borg
    "vorta",
    "warp",
    # GPU-accelerated cross-platform terminal emulator and multiplexer
    "wezterm",
    # Native desktop client for WhatsApp
    "whatsapp",
    # Network protocol analyzer
    "wireshark",
    # Allows access to WWDC livestreams, videos and sessions
    "wwdc",
]

[[packages.darwin.mas]]
name = "1Password for Safari"
id = 1569813296

[[packages.darwin.mas]]
name = "CiderTV"
id = 1065907486

[[packages.darwin.mas]]
name = "Convusic"
id = 1591366129

[[packages.darwin.mas]]
name = "DaisyDisk"
id = 411643860

[[packages.darwin.mas]]
name = "Data Jar"
id = 1453273600

[[packages.darwin.mas]]
name = "Developer"
id = 640199958

[[packages.darwin.mas]]
name = "Exporter"
id = 1099120373

[[packages.darwin.mas]]
name = "Hush"
id = 1544743900

[[packages.darwin.mas]]
name = "Iconic"
id = 1582751983

[[packages.darwin.mas]]
name = "Jayson"
id = 1468691718

[[packages.darwin.mas]]
name = "Keys Multiplatform"
id = 1494642810

[[packages.darwin.mas]]
name = "Landmarks"
id = 6446065798

[[packages.darwin.mas]]
name = "MakePass"
id = 1450989464

[[packages.darwin.mas]]
name = "Medis"
id = 1579200037

[[packages.darwin.mas]]
name = "MusicHarbor"
id = 1440405750

[[packages.darwin.mas]]
name = "MusicSmart"
id = 1512195368

[[packages.darwin.mas]]
name = "NepTunes"
id = 1006739057

[[packages.darwin.mas]]
name = "Notchmeister"
id = 1599169747

[[packages.darwin.mas]]
name = "Paprika Recipe Manager 3"
id = 1303222628

[[packages.darwin.mas]]
name = "Pi-hole Remote"
id = 1515445551

[[packages.darwin.mas]]
name = "Pixelmator Pro"
id = 1289583905

[[packages.darwin.mas]]
name = "rcmd"
id = 1596283165

[[packages.darwin.mas]]
name = "Save to Raindrop.io"
id = 1549370672

[[packages.darwin.mas]]
name = "Shazam"
id = 897118787

[[packages.darwin.mas]]
name = "StopTheMadness"
id = 1376402589

[[packages.darwin.mas]]
name = "TestFlight"
id = 899247664

[[packages.darwin.mas]]
name = "Things"
id = 904280696

[[packages.darwin.mas]]
name = "Vidimote"
id = 1585702412

[[packages.darwin.mas]]
name = "Vinegar"
id = 1591303229

[[packages.darwin.mas]]
name = "Wayback Machine"
id = 1472432422

[[packages.darwin.mas]]
name = "WorldWideWeb"
id = 1621370168


[vscode]
extensions = [
    "1password.op-vscode",
    "aaron-bond.better-comments",
    "alexcvzz.vscode-sqlite",
    "bbenoist.nix",
    "bierner.markdown-mermaid",
    "bradymholt.pgformatter",
    "bram209.leptos-language-server",
    "brettm12345.nixfmt-vscode",
    "casbin.vscode-casbin",
    "charliermarsh.ruff",
    "codezombiech.gitignore",
    "dakara.transformer",
    "davidanson.vscode-markdownlint",
    "dbaeumer.vscode-eslint",
    "esbenp.prettier-vscode",
    "fwcd.kotlin",
    "github.copilot-chat",
    "github.copilot-labs",
    "github.copilot",
    "github.vscode-github-actions",
    "gitlab.gitlab-workflow",
    "graphql.vscode-graphql-execution",
    "graphql.vscode-graphql-syntax",
    "graphql.vscode-graphql",
    "greenbyte.handlebars-preview",
    "gruntfuggly.todo-tree",
    "hashicorp.terraform",
    "hilleer.yaml-plus-json",
    "iliazeus.vscode-ansi",
    "jakebecker.elixir-ls",
    "karunamurti.tera",
    "lunaryorn.fish-ide",
    "mark-hansen.hledger-vscode",
    "mechatroner.rainbow-csv",
    "mrmlnc.vscode-duplicate",
    "ms-azuretools.vscode-docker",
    "ms-kubernetes-tools.vscode-kubernetes-tools",
    "ms-python.debugpy",
    "ms-python.isort",
    "ms-python.python",
    "ms-python.vscode-pylance",
    "ms-toolsai.jupyter-keymap",
    "ms-toolsai.jupyter-renderers",
    "ms-toolsai.jupyter",
    "ms-toolsai.vscode-jupyter-cell-tags",
    "ms-toolsai.vscode-jupyter-slideshow",
    "ms-vscode-remote.remote-containers",
    "ms-vscode-remote.remote-ssh-edit",
    "ms-vscode-remote.remote-ssh",
    "ms-vscode.remote-explorer",
    "ms-vsliveshare.vsliveshare",
    "nhoizey.gremlins",
    "prisma.prisma",
    "ratberryjam.open-in-gitup",
    "redhat.ansible",
    "redhat.vscode-xml",
    "redhat.vscode-yaml",
    "rust-lang.rust-analyzer",
    "serayuzgur.crates",
    "sgryjp.vscode-stable-sort",
    "simonsiefke.svg-preview",
    "skyapps.fish-vscode",
    "streetsidesoftware.code-spell-checker-bulgarian",
    "streetsidesoftware.code-spell-checker-swedish",
    "streetsidesoftware.code-spell-checker",
    "sumneko.lua",
    "svelte.svelte-vscode",
    "tamasfe.even-better-toml",
    "tauri-apps.tauri-vscode",
    "timonwong.shellcheck",
    "unifiedjs.vscode-mdx",
    "vadimcn.vscode-lldb",
    "Wokwi.wokwi-vscode",
]

[cargo]
bins = [
    "cargo-about",
    "cargo-audit",
    "cargo-dist",
    "cargo-edit",
    "cargo-espflash",
    "cargo-generate",
    "cargo-get",
    "cargo-leptos",
    "cargo-nextest",
    "cargo-run-bin",
    "cargo-semver-checks",
    "cargo-shuttle",
    "cargo-udeps",
    "cargo-watch",
    "create-tauri-app",
    "espup",
    "flamegraph",
    "lemmeknow",
    "rewrk",
    "tealdeer",
]
