[vscode]
extensions = [
    "1password.op-vscode",
    "aaron-bond.better-comments",
    "alexcvzz.vscode-sqlite",
    "bbenoist.nix",
    "bierner.markdown-mermaid",
    "bradymholt.pgformatter",
    "brettm12345.nixfmt-vscode",
    "casbin.vscode-casbin",
    "charliermarsh.ruff",
    "codezombiech.gitignore",
    "dakara.transformer",
    "davidanson.vscode-markdownlint",
    "dbaeumer.vscode-eslint",
    "earthly.earthfile-syntax-highlighting",
    "esbenp.prettier-vscode",
    "exercism.exercism-cli",
    "fwcd.kotlin",
    "github.vscode-github-actions",
    "gitlab.gitlab-workflow",
    "gleam.gleam",
    "golang.go",
    "graphql.vscode-graphql",
    "graphql.vscode-graphql-execution",
    "graphql.vscode-graphql-syntax",
    "greenbyte.handlebars-preview",
    "gruntfuggly.todo-tree",
    "hashicorp.terraform",
    "hilleer.yaml-plus-json",
    "iliazeus.vscode-ansi",
    "jakebecker.elixir-ls",
    "karunamurti.tera",
    "lunaryorn.fish-ide",
    "mark-hansen.hledger-vscode",
    "mechatroner.rainbow-csv",
    "mjmlio.vscode-mjml",
    "mkhl.direnv",
    "mrmlnc.vscode-duplicate",
    "ms-azuretools.vscode-docker",
    "ms-kubernetes-tools.vscode-kubernetes-tools",
    "ms-ossdata.vscode-postgresql",
    "ms-python.debugpy",
    "ms-python.isort",
    "ms-python.python",
    "ms-python.vscode-pylance",
    "ms-toolsai.jupyter",
    "ms-toolsai.jupyter-keymap",
    "ms-toolsai.jupyter-renderers",
    "ms-toolsai.vscode-jupyter-cell-tags",
    "ms-toolsai.vscode-jupyter-slideshow",
    "ms-vscode-remote.remote-containers",
    "ms-vscode-remote.remote-ssh",
    "ms-vscode-remote.remote-ssh-edit",
    "ms-vscode.remote-explorer",
    "ms-vsliveshare.vsliveshare",
    "myriad-dreamin.tinymist",
    "nefrob.vscode-just-syntax",
    "nhoizey.gremlins",
    "nvarner.typst-lsp",
    "prisma.prisma",
    "ratberryjam.open-in-gitup",
    "redhat.ansible",
    "redhat.vscode-commons",
    "redhat.vscode-xml",
    "redhat.vscode-yaml",
    "rust-lang.rust-analyzer",
    "sgryjp.vscode-stable-sort",
    "simonsiefke.svg-preview",
    "skyapps.fish-vscode",
    "streetsidesoftware.code-spell-checker",
    "streetsidesoftware.code-spell-checker-bulgarian",
    "streetsidesoftware.code-spell-checker-swedish",
    "sumneko.lua",
    "supermaven.supermaven",
    "svelte.svelte-vscode",
    "tamasfe.even-better-toml",
    "tauri-apps.tauri-vscode",
    "timonwong.shellcheck",
    "unifiedjs.vscode-mdx",
    "vadimcn.vscode-lldb",
    "wokwi.wokwi-vscode",
]
