tap "akeru-inc/tap"
tap "cjbassi/ytop"
tap "clementtsang/bottom"
tap "dandavison/delta", "https://github.com/dandavison/delta"
tap "dtan4/dtan4"
tap "filosottile/musl-cross"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "jesseduffield/lazydocker"
tap "mczachurski/wallpapper"
tap "nektos/tap"
tap "zbrox/repo"
# Cryptography and SSL/TLS Toolkit
brew "openssl@1.1"
# Interpreted, interactive, object-oriented programming language
brew "python@3.8"
# Automate deployment, configuration, and upgrading
brew "ansible"
# Collection of portable C++ source libraries
brew "boost"
# Standard SGML representation system for technical documents
brew "docbook"
# Source-code syntax highlighter
brew "source-highlight"
# Formatter/translator for text files to numerous formats. Includes a2x
brew "asciidoc"
# Text processor and publishing toolchain for AsciiDoc
brew "asciidoctor"
# Archival front-end
brew "atool"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Compiler infrastructure and toolchain library for WebAssembly
brew "binaryen"
# Parser generator
brew "bison"
# Core application library for C
brew "glib"
# Low-level library for pixel manipulation
brew "pixman"
# Vector graphics library with cross-device output support
brew "cairo"
# Easily generate Instruments traces for your rust crate
brew "cargo-instruments"
# Decentralized dependency manager for Cocoa
brew "carthage"
# Display user-friendly message boxes from shell scripts
brew "dialog"
# Cross-platform make
brew "cmake"
# Dependency manager for Cocoa projects
brew "cocoapods"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Load/unload environment variables based on $PWD
brew "direnv"
# Minimal, fast alternative to 'du -sh'
brew "diskus"
# Command-line tool for DigitalOcean
brew "doctl"
# More intuitive version of du in rust
brew "dust"
# Cross-platform C++ GUI toolkit (wxWidgets for macOS)
brew "wxmac"
# Programming language for highly scalable real-time systems
brew "erlang"
# Modern replacement for 'ls'
brew "exa"
# Command-line tool to interact with exercism.io
brew "exercism"
# Perl lib for reading and writing EXIF metadata
brew "exiftool"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Collection of GNU find, xargs, and locate
brew "findutils"
# User-friendly command-line shell for UNIX-like operating systems
brew "fish"
# Image format providing lossless and lossy compression for web images
brew "webp"
# Interpreter for PostScript and PDF
brew "ghostscript"
# Distributed revision control system
brew "git"
# Extensions to follow Vincent Driessen's branching model
brew "git-flow"
# Git extension for versioning large files
brew "git-lfs"
# Official GitLab CI runner
brew "gitlab-runner"
# C++ interface to glib
brew "glibmm"
# Command-line option parsing utility
brew "gnu-getopt"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# Validating, recursive, caching DNS resolver
brew "unbound"
# GNU Transport Layer Security (TLS) Library
brew "gnutls"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Colorize logfiles and command output
brew "grc"
# GNU grep, egrep and fgrep
brew "grep"
# Kubernetes package manager
brew "helm"
# Convert source code to formatted text with syntax highlighting
brew "highlight"
# Improved top (interactive process viewer)
brew "htop"
# Command-line benchmarking tool
brew "hyperfine"
# Database of common MIME types
brew "shared-mime-info"
# H.265/HEVC encoder
brew "x265"
# LLVM's OpenMP runtime library
brew "libomp"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# JSON output from a shell
brew "jo"
# Regular expressions library
brew "oniguruma"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Run local Kubernetes cluster in Docker
brew "kind"
# Tool to move from `docker-compose` to Kubernetes
brew "kompose"
# Asynchronous event library
brew "libev"
# Callback framework for C++
brew "libsigc++"
# C library implementing the SSH2 protocol
brew "libssh2"
# C websockets server library
brew "libwebsockets"
# C++ wrapper for libxml
brew "libxml++"
# GNOME XML library
brew "libxml2"
# Keep your Mac's application settings in sync
brew "mackup"
# Securely transfers data between computers
brew "magic-wormhole"
# Utility for directing compilation
brew "make"
# Mac App Store command-line interface
brew "mas"
# Replacement for the old crypt package and crypt(1) command
brew "mcrypt"
# Run a Kubernetes cluster locally
brew "minikube"
# High performance static file server
brew "miniserve"
# Simple tool to make locally trusted development certificates
brew "mkcert"
# Remote terminal application
brew "mosh"
# Port scanning utility for large networks
brew "nmap"
# Platform built on V8 to build network applications
brew "node"
# Libraries for security-enabled client and server applications
brew "nss"
# Manage multiple Node.js versions
brew "nvm"
# 7-Zip (high compression file archiver) implementation
brew "p7zip"
# Tool for creating identical machine images for multiple platforms
brew "packer"
# Cross-platform application and UI framework
brew "qt"
# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"
# Search PDFs for strings matching a regular expression
brew "pdfgrep"
# Convert bitmaps to vector graphics
brew "potrace"
# Modern replacement for ps written by Rust
brew "procs"
# Go support for Google's protocol buffers
brew "protoc-gen-go"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Intuitive find & replace CLI
brew "sd"
# Cross-shell prompt for astronauts
brew "starship"
# Tool Command Language
brew "tcl-tk"
# User interface to the TELNET protocol
brew "telnet"
# Tool to build, change, and version infrastructure
brew "terraform"
# Terminal multiplexer
brew "tmux"
# Manage complex tmux sessions easily
brew "tmuxinator"
# Program that allows you to count code, quickly
brew "tokei"
# CLI tool that moves files or folder to the trash
brew "trash"
# Vi 'workalike' with many additional features
brew "vim"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Internet file retriever
brew "wget"
# HTTP benchmarking tool
brew "wrk"
# Manipulate Xcode project files
brew "xcproj"
# Drop-in replacement for xcodebuild with a few extra features
brew "xctool"
# Fast CSV toolkit written in Rust
brew "xsv"
# JavaScript package manager
brew "yarn"
# Fast static site generator in a single binary with everything built-in
brew "zola"
# macOS app notarization helper
brew "akeru-inc/tap/xcnotary"
# A TUI system monitor written in Rust
brew "cjbassi/ytop/ytop"
# A cross-platform graphical process/system monitor with a customizable interface and a multitude of features.
brew "clementtsang/bottom/bottom"
# A viewer for git and diff output
brew "dandavison/delta/git-delta"
# `tail -f` experience for Kubernetes Pods
brew "dtan4/dtan4/k8stail"
# Linux cross compilers based on musl libc
brew "filosottile/musl-cross/musl-cross"
# A simple terminal UI for docker, written in Go
brew "jesseduffield/lazydocker/lazydocker"
# Run GitHub Actions locally
brew "nektos/tap/act"
cask "aerial"
cask "alacritty"
cask "alfred"
cask "bartender"
cask "bitbar"
cask "calibre"
cask "cheatsheet"
cask "chromedriver"
cask "cryptomator"
cask "dash"
cask "discord"
cask "docker"
cask "etcher"
cask "font-anonymice-powerline"
cask "font-dejavu-sans-mono-for-powerline"
cask "font-droid-sans-mono-for-powerline"
cask "font-fira-code"
cask "font-fira-mono-for-powerline"
cask "font-inconsolata-dz-for-powerline"
cask "font-inconsolata-for-powerline"
cask "font-inconsolata-g-for-powerline"
cask "font-jetbrains-mono"
cask "font-liberation-mono-for-powerline"
cask "font-menlo-for-powerline"
cask "font-meslo-for-powerline"
cask "font-monofur-for-powerline"
cask "font-noto-mono-for-powerline"
cask "font-roboto-mono-for-powerline"
cask "font-source-code-pro"
cask "font-source-code-pro-for-powerline"
cask "font-source-sans-pro"
cask "font-source-serif-pro"
cask "font-ubuntu-mono-derivative-powerline"
cask "gitter"
cask "gitup"
cask "google-chrome"
cask "handbrake"
cask "iterm2"
cask "keepingyouawake"
cask "kitematic"
cask "ksdiff"
cask "lastfm"
cask "macdown"
cask "mounty"
cask "openttd"
cask "osxfuse"
cask "paw"
cask "plex"
cask "postico"
cask "quicklook-csv"
cask "quicklook-json"
cask "rectangle"
cask "rocket"
cask "screens"
cask "sequel-pro"
cask "slack"
cask "steam"
cask "sublime-text"
cask "teamviewer"
cask "transmit"
cask "vagrant"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "viscosity"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
cask "wireshark"
cask "wwdc"
mas "1Password 7", id: 1333542190
mas "Abyss", id: 1507396839
mas "Cardhop", id: 1290358394
mas "CleanMyMac X", id: 1339170533
mas "DaisyDisk", id: 411643860
mas "Day One", id: 1055511498
mas "Developer", id: 640199958
mas "Diagrams", id: 1276248849
mas "Downlink", id: 1454269192
mas "Drop", id: 1173932628
mas "Finances", id: 1218241304
mas "Gemini 2", id: 1090488118
mas "Ghostery Lite", id: 1436953057
mas "Grammarly for Safari", id: 1462114288
mas "IconFly", id: 556381974
mas "Jira", id: 1475897096
mas "Kaleidoscope", id: 587512244
mas "Keynote", id: 409183694
mas "Lingo", id: 624884154
mas "Medis", id: 1063631769
mas "Messenger", id: 1480068668
mas "Myna for Google Translate", id: 1100290134
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Paprika Recipe Manager 3", id: 1303222628
mas "PDFOptim", id: 621276561
mas "Photo Privacy", id: 428752671
mas "Pixelmator", id: 407963104
mas "Shazam", id: 897118787
mas "SnippetsLab", id: 1006087419
mas "Soulver", id: 413965349
mas "Telegram", id: 747648890
mas "The Unarchiver", id: 425424353
mas "Things", id: 904280696
mas "ToothFairy", id: 1191449274
mas "WhatsApp", id: 1147396723
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835
