[settings.cargo]
binstall = true
binstall_native = true

[tools]
rust = "stable"
"cargo:cargo-about" = "latest"
"cargo:cargo-audit" = "latest"
"cargo:cargo-generate" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-semver-checks" = "latest"
"cargo:cargo-udeps" = "latest"
"cargo:cargo-watch" = "latest"
"cargo:espup" = "latest"
"cargo:flamegraph" = "latest"
"cargo:lazyjj" = "latest"
