# documentation at https://starship.rs/config
format = """$directory$character"""
right_format = """$all"""

[character]
success_symbol = "➜"
error_symbol = "✗"

[cmd_duration]
min_time = 500
show_milliseconds = true
format = "отне [$duration]($style) "
show_notifications = true

[directory]
home_symbol = "🏠"

[battery]
disabled = true

[direnv]
disabled = false
style = "#CE9178"

[gcloud]
disabled = true

[git_branch]
format =  '[$symbol$branch(:$remote_branch)]($style)'
